### ISSUE TITLE
Available modes

### ISSUE THREAD

**Issue by Glacian22** [ling1726/cypress-forced-colors#3]
You might want to clarify in the readme that there are two valid parameters, 'light' and 'dark' (according to your type definition).

Also, you mentioned that this can be used to test high contrast mode without relying on enabling it in Windows, could you elaborate? Thanks!

**Comment by ling1726** [comment]
Hi @Glacian22, in chromium >98, there was a developer flag created that would 'emulate' windows high contrast mode with a mock theme. This plugin simply calls the cdp command to enable the HC mock theme.

There are 2 mock these 'light' and 'dark' which correspond to the 2 typical color schemes in windows high contrast

**Comment by Glacian22** [comment]
Ah gotcha, thanks!
